### ISSUE TITLE
kuri_gazebo needs to be removed

### ISSUE THREAD

**Issue by mayacakmak** [robotic-picker-sp22/fetch-picker#3]
Looks like kuri_gazebo comes up as part of an install, it won't break anything but might be good to remove.

@Zyu75 @vinitha910

**Comment by mayacakmak** [comment]
@vinitha910 Did you identify this instance and remove it?

Looks like there is also residual code in the stater code  (a kuri/ sub folder?) that needs to be removed.

thanks.
-maya

**Comment by vinitha910** [comment]
Sorry again for the late response, wasn't getting notifications. I removed kuri-related folders.
