### ISSUE TITLE
Week 3 Labs

### ISSUE THREAD

**Issue by mayacakmak** [robotic-picker-sp22/fetch-picker#5]
@vinitha910 @Zyu75 I have added the labs for Week 3, they looks straightforward but I'll keep looking through to see if there's anything to update and it would be great if you can also go through the steps to make sure everything works as expected.

**TODOs so far:**
- [ ]  Need to replace screenshot and update version reference here: https://github.com/robotic-picker-sp22/fetch-picker/wiki/Lab-13%3A-Creating-Interactive-Visualizations-in-RViz-using-InteractiveMarkers

Thanks!
-Maya

**Comment by ironmanyu** [comment]
Sure. I will start working on it today.

**Comment by ironmanyu** [comment]
Hi, I just all cse481wi19 into cse481c. I changed them to techin517 in the techin517 sets but I find that techin517 and cse481 share the same source, thus I just change it to cse481c as the first week labs.  
![image](https://user-images.githubusercontent.com/76197784/163766075-e6e02a34-3e32-421e-a61b-8415bd0327dd.png)

**Comment by ironmanyu** [comment]
Hi,
Students reflect that there is a command in lab 18 does not work:
sudo apt-get install ros-noetic-rosbridge-server ros-noetic-tf2-web-republisher ros-noetic-interactive-marker-proxy
![image](https://user-images.githubusercontent.com/76197784/164303193-e6108743-99f6-49b3-bfef-8807457881af.png)

The issue is that ROS noetic does not have "interactive-marker-proxy". Then I recommend them to install from the Github source. Are there any other ideas that we can solve this kind of issue?

**Comment by mayacakmak** [comment]
@vinitha910 Can you keep Zhitao in the loop about any change to the labs as you debug/fix them?

There were some issues with Lab 18 that I believe got resolved on the capstone side but were not documented here on Github (perhaps it was on Canvas?). We might be running into the same issues here and useful to know the solutions.

Also it sounded like the solution to issues in lab 18 introduced other issues in later labs? -> Definitely something we'd like to avoid, happy to discuss possible longer term solutions.

thanks!
-maya

**Comment by vinitha910** [comment]
Sorry I'm just seeing this, I wasn't getting notifications. The solution is to remove ros-noetic-interactive-marker-proxy. I tried installing it from source but I had to make changes to interactive marker and install that from source as well which causes Rviz to crash. interactive-marker-proxy is not needed to complete the lab so I removed it from the wiki.
