### ISSUE TITLE
Week 4 issues

### ISSUE THREAD

**Issue by mayacakmak** [robotic-picker-sp22/fetch-picker#6]
In Lab 26 I removed all references to the 'assignment' (in general we want assignments to reference the labs but not the other way around -- to make sure someone not taking the class can still go through the labs as a tutorial). (Also it was Assignment 5 last year, it is Assignment 4 this year, so it's not ideal to have to change it every year ;)) As part of the lab there was reference to a file called `a5_obstables.py` and I changed that to `lab26_obstacles.py` but that change probably needs to be reflected to the actual codebase as well. Can someone take a look?
https://github.com/robotic-picker-sp22/fetch-picker/wiki/Lab-26%3A-Advanced-interactive-markers

Let me know if you discover any other issues.
@vinitha910 @Zyu75

**Comment by ironmanyu** [comment]
In my opinion, students need to create the lab26_obstacles.py by themselves shown in the figure below:
![image](https://user-images.githubusercontent.com/76197784/164082369-53b0e8db-fb6d-4de1-9a3b-2966630b878a.png)

Thus we just need to modify the code in the corresponding code on the wiki, which we did as the figure shows.

**Comment by vinitha910** [comment]
@ironmanyu updates fixes this issue!
